services:
  ipa:
    image: ${REGISTRY}/ci-ipa:${TAG}
    container_name: ipa
    hostname: master.ipa.test
    dns: 172.16.100.2
    env_file: ./env.containers
    volumes:
    - ./shared:/shared:rw
    cap_add:
    - SYS_ADMIN
    - SYS_PTRACE
    - AUDIT_WRITE
    - SYS_CHROOT
    - NET_ADMIN
    security_opt:
    - apparmor=unconfined
    - label=disable
    - seccomp=unconfined
    networks:
      ipa-tuura:
        ipv4_address: 172.16.100.10

  ipa-tuura:
    image: quay.io/idmops/bridge:latest
    container_name: ipa-tuura
    hostname: ipa-tuura.bridge.test
    dns: 172.16.100.2
    env_file: ./env.containers
    volumes:
    - ./shared:/shared:rw
    cap_add:
    - SYS_ADMIN
    - SYS_PTRACE
    - SYS_CHROOT
    - AUDIT_WRITE
    security_opt:
    - apparmor=unconfined
    - label=disable
    - seccomp=unconfined
    networks:
      ipa-tuura:
        ipv4_address: 172.16.100.14

  ldap:
    image: ${REGISTRY}/ci-ldap:${TAG}
    container_name: ldap
    hostname: master.ldap.test
    dns: 172.16.100.2
    env_file: ./env.containers
    volumes:
    - ./shared:/shared:rw
    cap_add:
    - SYS_PTRACE
    - AUDIT_WRITE
    security_opt:
    - apparmor=unconfined
    - label=disable
    - seccomp=unconfined
    networks:
      ipa-tuura:
        ipv4_address: 172.16.100.20

  client:
    image: ${REGISTRY}/ci-client:${TAG}
    container_name: client
    hostname: client.test
    dns: 172.16.100.2
    env_file: ./env.containers
    volumes:
    - ./shared:/shared:rw
    cap_add:
    - SYS_ADMIN
    - SYS_PTRACE
    - AUDIT_WRITE
    security_opt:
    - apparmor=unconfined
    - label=disable
    - seccomp=unconfined
    networks:
      ipa-tuura:
        ipv4_address: 172.16.100.40

networks:
  ipa-tuura:
    name: ipa-tuura-ci
    driver: bridge
    ipam:
     config:
       - subnet: 172.16.100.0/24
         gateway: 172.16.100.1
     options:
        driver: host-local
