version: "3"
services:
  tuura-server:
    container_name: tuura-server
    build:
      context: ../..
      dockerfile: src/prod/Containerfile
    ports:
      - 8005:80
      - 3501:3500
      - 4701:81
      - 4430:443
    command: sh -c "echo "baeldung" && echo "docker" "
